routes/web.php
<?php

use App\Http\Controllers\CartController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
// Route::post('/', 'HomeController@store');

Auth::routes();

Route::resource('product', 'ProductController');
Route::resource('order', 'OrderController')->only([
    'edit', 'update'
]);
Route::resource('category', 'CategoryController')->only([
    'show'
]);

Route::get('/shop', 'ShopController@index');
Route::post('/shop', 'ShopController@store');
Route::get('/cart', 'CartController@index');
Route::post('/cart', 'CartController@store');

// Route::get('cart', [CartController::class, 'cartList'])->name('cart.list');
// Route::post('cart', [CartController::class, 'addToCart'])->name('cart.store');
// Route::post('update-cart', [CartController::class, 'updateCart'])->name('cart.update');
// Route::post('remove', [CartController::class, 'removeCart'])->name('cart.remove');
// Route::post('clear', [CartController::class, 'clearAllCart'])->name('cart.clear');

// Route::get('/auth', 'HomeController@index')->name('auth');

resources/views/admin/create.blade.php
@extends('layouts.master')

@section('content')

    <section class="padding_top">
        <div class="container">
            <form action="{{ route('product.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" name="name" value="{{ old('name', '') }}" class="form-control">
                        @error('name')
                            <div class="alert alert-danger" role="alert">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Price</label>
                        <input type="number" name="price" value="{{ old('price', '') }}" class="form-control">
                        @error('price')
                        <div class="alert alert-danger" role="alert">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Weight</label>
                        <input type="number" name="weight" value="{{ old('weight', '') }}" class="form-control">
                        @error('weight')
                        <div class="alert alert-danger" role="alert">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Stock</label>
                        <input type="number" name="stock" value="{{ old('stock', '') }}" class="form-control">
                        @error('stock')
                        <div class="alert alert-danger" role="alert">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Description</label>
                        <textarea class="form-control" name="description" rows="3"> {{ old('description', '') }} </textarea>
                        @error('description')
                        <div class="alert alert-danger" role="alert">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Category</label> <br>
                        <select name="categories_id" class="form-control">
                            <option value="">-- Select Category --</option>
                                @foreach ($categories as $category)
                                    <option value="{{$category->id}}">{{$category->name}}</option>
                                @endforeach
                        </select> <br><br>
                        @error('category_id')
                        <div class="alert alert-danger" role="alert">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Image</label>
                        <input type="text" name="image" class="form-control">
                        @error('image')
                        <div class="alert alert-danger" role="alert">{{ $message }}</div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
        </div>
    </section>
@endsection

resources/views/admin/edit.blade.php
@extends('layouts.master')

@section('content')

    <section class="padding_top">
        <div class="container">
            <form action="{{route ('product.update', $product->id)}}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" name="name" value="{{ $product->name }}" class="form-control">
                        @error('name')
                            <div class="alert alert-danger" role="alert">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Price</label>
                        <input type="number" name="price" value="{{ $product->price }}" class="form-control">
                        @error('price')
                        <div class="alert alert-danger" role="alert">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Weight</label>
                        <input type="number" name="weight" value="{{ $product->weight }}" class="form-control">
                        @error('weight')
                        <div class="alert alert-danger" role="alert">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Stock</label>
                        <input type="number" name="stock" value="{{ $product->stock }}" class="form-control">
                        @error('stock')
                        <div class="alert alert-danger" role="alert">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Description</label>
                        <textarea class="form-control" name="description" rows="3"> {{ $product->description }} </textarea>
                        @error('description')
                        <div class="alert alert-danger" role="alert">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Category</label> <br>
                        <select name="categories_id" class="form-control">
                            <option value="">-- Select Category --</option>
                                @foreach ($categories as $category)
                                @if ($category->id === $product->categories_id)
                                    <option value="{{$category->id}}" selected>{{$category->name}}</option>
                                @else
                                    <option value="{{$category->id}}">{{$category->name}}</option>
                                @endif
                                @endforeach
                        </select> <br><br>
                        @error('category_id')
                        <div class="alert alert-danger" role="alert">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label>Image</label>
                        <input type="file" name="image" class="form-control">
                        @error('image')
                        <div class="alert alert-danger" role="alert">{{ $message }}</div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Update</button>
                </form>
        </div>
    </section>

@endsection    

resources/views/admin/index.blade.php
@extends('layouts.master')

@push('style')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
@endpush

@section('content')

    <div class="container padding_top">
        <a href="/product/create" class="genric-btn primary radius mb-3">Create New Product</a>
        <table id="list-product" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Weight</th>
                    <th>Stock</th>
                    <th>Category</th>
                    <th>Description</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                    @forelse ($products as $product)
                        <tr>
                        <td>{{ $product->id }}</td>
                        <td>
                            @if (Str::contains($product->image, 'https:/'))
                                <img src="{{$product->image}}" alt="image" height="75px">
                            @else
                                <img src="{{ asset('images/product/'.$product->image)}}" alt="image" height="75px">
                            @endif
                        </td>
                        <td>{{ $product->name }}</td>
                        <td>{{ $product->price }}</td>
                        <td>{{ $product->weight }}</td>
                        <td>{{ $product->stock }}</td>
                        <td>{{ $product->category->name }}</td>
                        <td>{{ $product->description }}</td>
                        <td class="d-flex justify-content-around">
                            <a href="/product/{{$product->id}}/edit" class="btn btn-warning btn-sm">Edit</a>
                            <form action="/product/{{$product->id}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                            </form>
                        </td>
                        </tr>
                    @empty
                        <td colspan="4" class="text-center">No Product</td>
                    @endforelse
            </tbody>
        </table>
    </div>
@endsection

@push('script')
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.js"></script>
  <script>
    $(function () {
      $("#list-product").DataTable();
    });
  </script>
@endpush